spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
bySMA:
  rabbitmq:
    queue:
      name: q1bySMA
    jsonQueue:
      name: jsonQueubySMA
      routingKey: routingKeyForJSONQueue
    exchange:
      name: ex1bySMA
    routingKey: rk1bySMA
